### ISSUE TITLE
GAMES endpoint doesn't return proper image id

### ISSUE THREAD

**Issue by KarenK1995** [husnjak/IGDB-SWIFT-API#15]
I am fetching the games list following the provided example 

wrapper.apiProtoRequest(endpoint: .GAMES, apicalypseQuery: "fields *;", dataResponse: { bytes in
          let games: [Proto_Game] = try! Proto_GameResult(serializedData: bytes) // This converts Binary to a struct
      }, errorResponse: { error in
          // Do Something
      })

Then I want to find the image ids so I can use the imageBuilder function to get the urls but the resulting url is not a valid image url. The website uses cloudinary_id for urls but those ids are missing from the reponse of games endpoint.

**Comment by husnjak** [comment]
You should look over your query, you are not requesting the image IDs.
More information about querying can be found here https://api-docs.igdb.com/#expander 

You should check out the IGDB discord server for more help regarding queries, you should get help much faster there
