### ISSUE TITLE
Swift 5?

### ISSUE THREAD

**Issue by juavazmor** [husnjak/IGDB-SWIFT-API#4]
I'm trying to build a quick app using Swift 5 and I can't get it working. Do you have any plans of upgrading it to the last version?

Thanks for your work!

**Comment by husnjak** [comment]
I'll look into the issue, but I have set the swift project version as Undefined so it should work. 
What issue are you getting?

**Comment by juavazmor** [comment]
Looks like the problem is coming because a dependency called "Just". "Pods/Just/Just.swift"

In multiple lines there are Strings still using the deprecated "characters" property. This one is easy to fix but... In lines 331 and 334 of the same file I got two more errors:

`Cannot convert return expression of type 'Dictionary<Key, Value>.Keys' to return type 'LazyMapSequence<[Key : Value], Key>'`
`Cannot convert return expression of type 'Dictionary<Key, Value>.Values' to return type 'LazyMapSequence<[Key : Value], Value>'`

**Comment by husnjak** [comment]
The package has been updated and should work with swift 5 now
