### ISSUE TITLE
IGDBWrapper.apiRequest (Achievements?) crash

### ISSUE THREAD

**Issue by joekw** [husnjak/IGDB-SWIFT-API#5]
I just submitted an update to my app with this wrapper and seeing a few crashes, not sure where they're coming from. 

This is all I'm getting from the Xcode crash report.

```
#3	(null) in closure #1 in IGDBWrapper.achievements(apiCalypse:result:errorResponse:) ()
#5	0x0000000104e8ac30 in closure #1 in IGDBWrapper.apiRequest(endpoint:apicalypseQuery:dataResponse:errorResponse:) at /Pods/IGDB-SWIFT-API/IGDB-SWIFT-API/Classes/Wrapper/IGDBWrapper.swift:24
```

Any ideas?
(I'm not using the achievements endpoint anywhere in my code so not sure why it's mentioning that?)

**Comment by joekw** [comment]
I'm seeing a lot of crashes for this reason now and still no idea where it's coming from.

**Comment by husnjak** [comment]
Achievements have been removed as of this new release. 
I'm going to close this ticket for now, if this happens again please open another one and i'll investigate
