### ISSUE TITLE
Total Number of results /count

### ISSUE THREAD

**Issue by jamirmachado** [husnjak/IGDB-SWIFT-API#9]
I noticed that I can make a call to `https://api.igdb.com/v4/games/count` and get the total Number of results.
Is this supported currently? I'm trying to make a pagination using the offset.

Also, thanks for this great wrapper!

**Comment by husnjak** [comment]
I think that this is already supported, but I'll look into it.

**Comment by husnjak** [comment]
Pushed an update to the project that adds support for Count

https://github.com/husnjak/IGDB-SWIFT-API/releases/tag/0.3.4
